spring:
  application:
    name: pretest

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 20
        format_sql: true
        show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Password11!

logging:
  level:
    root: INFO
    dev.kurtyoon.pretest: DEBUG